### ISSUE TITLE
[Lint]: Why using excessive precision on float?

### ISSUE THREAD

**Issue by fu050409** [yaoshiu/pretty-der6y#34]
In [Failed CI Checks](https://github.com/yaoshiu/pretty-der6y/actions/runs/10972311174/job/30468425520):

![image](https://github.com/user-attachments/assets/854e0ab2-2883-4fbe-a887-3496832f2c13)

An error actually occured. Why use `0.59999999999999998` here?

**Comment by yaoshiu** [comment]
Because it is the default pace_range value in the official client, I tried to mimic the behavior of the official client as much as possible. I have noticed this error, but I don't have time to fix it at the moment. Just simply replace the type of pace_range with f64 will do the trick I think.
